// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz047Kgz1FZb0c5hV-UQqkR7TxgTsL8xY',
    appId: '1:66071509812:web:7a47b7a746a059de818361',
    messagingSenderId: '66071509812',
    projectId: 'bookpulse-58e07',
    authDomain: 'bookpulse-58e07.firebaseapp.com',
    storageBucket: 'bookpulse-58e07.firebasestorage.app',
    measurementId: 'G-L9436386VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKSruQct7HziDtcsFLU91VrRyXlTNLnm0',
    appId: '1:66071509812:android:7500bdc5437de097818361',
    messagingSenderId: '66071509812',
    projectId: 'bookpulse-58e07',
    storageBucket: 'bookpulse-58e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1jUQ2MWr1x_JQBIWR-2el0A3ifuFgR6k',
    appId: '1:66071509812:ios:53465d74bbe31535818361',
    messagingSenderId: '66071509812',
    projectId: 'bookpulse-58e07',
    storageBucket: 'bookpulse-58e07.firebasestorage.app',
    iosBundleId: 'com.bookpul',
  );
}
